name: time_tracker
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Local Storage
  #localstorage: ^5.0.0
  
  # Utilities
  intl: ^0.20.2
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/timetrackerlogo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
